### ISSUE TITLE
Coquille auth.svg

### ISSUE THREAD

**Issue by marzikill** [glassus/terminale_nsi#6]
Bonjour Gilles,

J'ai utilisé tes infographies pour mon cours de terminale, bravo et merci pour ton travail c'est extrêmement clair ! Ça a dû te prendre un sacré bout de temps.
J'ai remarqué une petite coquille dans le fichier auth.svg cependant, il y a deux fois "Étape 7" je ne sais pas si cela est voulu. Je te joins le fichier modifié.

![auth](https://github.com/glassus/terminale_nsi/assets/24573818/ec013c2d-b6eb-4a0a-9b1d-0aac5fd7620f)

Amitiés,
Florian.

**Comment by glassus** [comment]
Bonjour Florian,
merci pour ta vigilance et pour tes compliments !
J'ai intégré ta correction.
a+

Gilles
